fix(web/test): mock exceptions properly in ApplicationServiceSpec
by using

>> { throw exception }

instead of

>> exception

so spock doesn't try to coerce the exception into the return type of the method, with errors like:

ApplicationServiceSpec > when UseFront50AsSourceOfTruth: #checkFront50 and application exists only in clouddriver, but front50 throws an exception > com.netflix.spinnaker.gate.ApplicationServiceSpec.when UseFront50AsSourceOfTruth: true and application exists only in clouddriver, but front50 throws an exception STANDARD_OUT
    --------------- Test when UseFront50AsSourceOfTruth: #checkFront50 and application exists only in clouddriver, but front50 throws an exception
    2024-09-10 19:21:01.226 ERROR   --- [pool-5-thread-1] c.n.s.gate.services.ApplicationService   : [] Falling back to application cache
    org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'java.lang.Exception: fatal exception' with class 'java.lang.Exception' to class 'java.util.Map'
    	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:404)
    	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:315)
    	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:243)
    	at org.spockframework.runtime.GroovyRuntimeUtil.coerce(GroovyRuntimeUtil.java:49)
    	at org.spockframework.mock.response.ConstantResponseGenerator.doRespond(ConstantResponseGenerator.java:35)
    	at org.spockframework.mock.response.SingleResponseGenerator.respond(SingleResponseGenerator.java:32)
    	at org.spockframework.mock.response.ResponseGeneratorChain.respond(ResponseGeneratorChain.java:44)
    	at org.spockframework.mock.runtime.MockInteraction.accept(MockInteraction.java:73)
    	at org.spockframework.mock.runtime.MockInteractionDecorator.accept(MockInteractionDecorator.java:50)
    	at org.spockframework.mock.runtime.InteractionScope$1.accept(InteractionScope.java:57)
    	at org.spockframework.mock.runtime.MockController.handle(MockController.java:40)
    	at org.spockframework.mock.runtime.JavaMockInterceptor.intercept(JavaMockInterceptor.java:86)
    	at org.spockframework.mock.runtime.DynamicProxyMockInterceptorAdapter.invoke(DynamicProxyMockInterceptorAdapter.java:34)
    	at jdk.proxy3/jdk.proxy3.$Proxy96.getApplication(Unknown Source)
    	at com.netflix.spinnaker.gate.services.ApplicationService$Front50ApplicationRetriever$_callWithMdc_closure1.doCall(ApplicationService.groovy:533)
    	at com.netflix.spinnaker.gate.services.ApplicationService$Front50ApplicationRetriever$_callWithMdc_closure1.call(ApplicationService.groovy)
    	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$wrapCallableForPrincipal$0(AuthenticatedRequest.java:272)
    	at com.netflix.spinnaker.gate.services.ApplicationService$Front50ApplicationRetriever.callWithMdc(ApplicationService.groovy:531)
    	at com.netflix.spinnaker.gate.services.ApplicationService$Front50ApplicationRetriever.callWithMdc(ApplicationService.groovy)
    	at com.netflix.spinnaker.gate.services.MdcWrappedCallable.call(MdcWrappedCallable.java:41)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	at java.base/java.lang.Thread.run(Thread.java:833)