refactor(test): add EmbeddedRedis to get connection pool for test execution during upgrade to spring boot 2.7.x
While upgrading spring boot 2.7.18, encounter below error during test compilation of gate-web module:
```
Unexpected exception thrown: java.lang.AssertionError:
Expecting:
 <Unstarted application context org.springframework.boot.test.context.assertj.AssertableApplicationContext[startupFailure=org.springframework.context.ApplicationContextException]>
to get beans of type:
 <org.springframework.session.data.redis.config.ConfigureRedisAction>:
but context failed to start:
 org.springframework.context.ApplicationContextException: Failed to start bean 'springSessionRedisMessageListenerContainer'; nested exception is org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
```
The `com.netflix.spinnaker.gate.config.RedisConfigTest.testCircularDependenciesException` and `com.netflix.spinnaker.gate.config.RedisConfigTest.testCircularDependenciesExceptionSecure` tests generated the above error. The root cause is unavailability of redis resource pool. So, adding EmbeddedRedis to provide resource pool during test execution.