fix(web/test): explicitly enable retrofit
to see if it fixes

Caused by:
org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.gate.services.internal.OrcaServiceSelector]: Factory method 'orcaServiceSelector' threw exception; nested exception is com.netflix.spinnaker.kork.exceptions.SystemException: No service client provider found for url (http://localhost:8083)
    at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
    at app//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
    ... 135 more
    Caused by:
    com.netflix.spinnaker.kork.exceptions.SystemException: No service client provider found for url (http://localhost:8083)
        at app//com.netflix.spinnaker.config.DefaultServiceClientProvider.lambda$findProvider$1(DefaultServiceClientProvider.java:64)
        at java.base@17.0.12/java.util.Optional.orElseThrow(Optional.java:403)
        at app//com.netflix.spinnaker.config.DefaultServiceClientProvider.findProvider(DefaultServiceClientProvider.java:61)
        at app//com.netflix.spinnaker.config.DefaultServiceClientProvider.getService(DefaultServiceClientProvider.java:53)
        at app//com.netflix.spinnaker.gate.config.GateConfig.buildService(GateConfig.groovy:283)
        at app//com.netflix.spinnaker.gate.config.GateConfig.access$0(GateConfig.groovy)
        at app//com.netflix.spinnaker.gate.config.GateConfig$_createClientSelector_closure2.doCall(GateConfig.groovy:298)
        at app//com.netflix.spinnaker.gate.config.GateConfig$_createClientSelector_closure2.call(GateConfig.groovy)
        at app//org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3601)
        at app//org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3586)
        at app//org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3686)
        at app//com.netflix.spinnaker.gate.config.GateConfig.createClientSelector(GateConfig.groovy:293)
        at app//com.netflix.spinnaker.gate.config.GateConfig.orcaServiceSelector(GateConfig.groovy:125)
        at app//com.netflix.spinnaker.gate.config.GateConfig$$EnhancerBySpringCGLIB$$111731ef.CGLIB$orcaServiceSelector$9(<generated>)
        at app//com.netflix.spinnaker.gate.config.GateConfig$$EnhancerBySpringCGLIB$$111731ef$$FastClassBySpringCGLIB$$3437c034.invoke(<generated>)
        at app//org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at app//org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at app//com.netflix.spinnaker.gate.config.GateConfig$$EnhancerBySpringCGLIB$$111731ef.orcaServiceSelector(<generated>)
        at java.base@17.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17.0.12/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17.0.12/java.lang.reflect.Method.invoke(Method.java:569)
        at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 136 more

from https://github.com/spinnaker/gate/actions/runs/10302439765/job/28516563296